=== kaelri/cortex-prime-character-sheet/schema/0.1/character.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://cortex.engard.me/schema/0.1/character.schema.json",
	"title": "Cortex Prime character",
	"description": "A JSON schema for a Cortex Prime player character sheet.",
	"type" : "object",
	"$defs": {
		"traitSet": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"description": "The name of the trait set."
				},
				"description": {
					"type": "string",
					"description": "A description of the trait set."
				},
				"nounSingular": {
					"type": "string",
					"description": "The singular noun used to describe a trait in this set."
				},
				"nounPlural": {
					"type": "string",
					"description": "The plural noun used to describe multiple traits in this set."
				},
				"traits": {
					"type": "array",
					"description": "The traits in the trait set.",
					"items": { "$ref": "#/$defs/trait" }
				},
				"sfx": {
					"type": "array",
					"description": "Any SFX attached directly to this trait set.",
					"items": { "$ref": "#/$defs/sfx" }
				},
				"tags": { "$ref": "#/$defs/tags" },
				"custom": { "$ref": "#/$defs/custom" }
			},
			"additionalProperties": false,
			"required": [ "name", "description", "nounSingular", "nounPlural", "traits", "sfx", "tags", "custom" ]
		},
		"trait": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"description": "The name of the trait."
				},
				"value": {
					"type": "integer",
					"description": "The die value of the trait. For example, `2` for d2, `6` for a d6, etc. For unrated traits, use `0`."
				},
				"description": {
					"type": "string",
					"description": "A description of the trait, or the trait statement."
				},
				"traits": {
					"type": "array",
					"description": "Any child traits attached this parent trait.",
					"items": { "$ref": "#/$defs/trait" }
				},
				"sfx": {
					"type": "array",
					"description": "Any SFX attached to this trait.",
					"items": {
						"oneOf": [
							{"$ref": "#/$defs/sfx"},
							{"$ref": "#/$defs/sfxHinder"}
						]
					}
				},
				"tags": { "$ref": "#/$defs/tags" },
				"custom": { "$ref": "#/$defs/custom" }
			},
			"additionalProperties": false,
			"required": [ "name", "value", "description", "traits", "sfx", "tags", "custom" ]
		},
		"sfx": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"description": "The name of the SFX."
				},
				"description": {
					"type": "string",
					"description": "A description of the SFX."
				},
				"tags": { "$ref": "#/$defs/tags" },
				"custom": { "$ref": "#/$defs/custom" }
			},
			"additionalProperties": false,
			"required": [ "name", "description", "tags", "custom" ]
		},
		"sfxHinder": {
			"type": "string",
			"description": "Represents the “Hinder” core SFX.",
			"enum": [ "hinder" ]
		},
		"tags": {
			"type": "array",
			"description": "A list of taxonomy tags attached to this entity. Tags may include letters, numbers, hyphens, periods, and forward slashes (for namespacing).",
			"items": {
				"type": "string",
				"pattern": "^[A-Za-z0-9-\\.\\\/]+$"
			}
		},
		"custom": {
			"type": "object",
			"description": "An open-ended object where apps and services can add custom data to this entity. It is strongly recommended that developers compartmentalize their app’s custom data under a unique key to avoid conflicts and generally be good neighbors.",
			"additionalProperties": true
		}
	},
	"properties": {
		"$schema": {
			"description": "JSON schema URI for character.schema.json.",
			"type": "string"
		},
		"version": {
			"description": "Version of character.schema.json to use.",
			"type": "string",
			"enum": [ "0.1" ]
		},
		"id": {
			"type": "string",
			"description": "A unique identifier for the character.",
			"format": "uuid"
		},
		"dateCreated": {
			"type": "string",
			"format": "date-time",
			"description": "The date and time when the character was first created."
		},
		"dateModified": {
			"type": "string",
			"format": "date-time",
			"description": "The date and time when the character was last changed."
		},
		"dateTouched": {
			"type": "string",
			"format": "date-time",
			"description": "The date and time when the character was last loaded, viewed or interacted with."
		},
		"name": {
			"type": "string",
			"description": "The character’s name."
		},
		"game": {
			"type": "string",
			"description": "The name of the game or campaign that the character belongs to."
		},
		"pronouns": {
			"type": "string",
			"description": "The character’s preferred pronouns."
		},
		"description": {
			"type": "string",
			"description": "A short summary or subtitle for the character."
		},
		"traitSets": {
			"type": "array",
			"description": "The character’s trait sets.",
			"items": { "$ref": "#/$defs/traitSet" }
		},
		"portrait": {
			"type": "object",
			"description": "An image to represent the character.",
			"properties": {
				"url": {
					"type": "string",
					"description": "A URI compatible with the HTML <image> tag.",
					"format": "uri"
				},
				"alt": {
					"type": "string",
					"description": "A description of the image."
				},
				"tags": { "$ref": "#/$defs/tags" },
				"custom": { "$ref": "#/$defs/custom" }
			},
			"required": [ "url", "alt", "tags", "custom" ],
			"additionalProperties": false
		},
		"plotPoints": {
			"type": "integer",
			"description": "The character’s current number of plot points."
		},
		"notes": {
			"type": "string",
			"description": "Any additional notes about the character. Format: plaintext, Markdown or HTML."
		},
		"tags": { "$ref": "#/$defs/tags" },
		"custom": { "$ref": "#/$defs/custom" }
	},
	"required": [ "version", "id", "dateCreated", "dateModified", "dateTouched", "name", "game", "pronouns", "description", "traitSets", "portrait", "plotPoints", "notes", "tags", "custom" ],
	"additionalProperties": false
}

=== kaelri/cortex-prime-character-sheet/data/templates/Sendak_Eggers.cortex.json
{
  "$schema": "https://cortex.engard.me/schema/0.1/character.schema.json",
  "version": "0.1",
  "id": "bf62d3dc-de68-430c-a0cf-a2a16752c261",
  "dateCreated": "2024-03-25T14:21:43.746Z",
  "dateModified": "2024-03-25T14:21:43.746Z",
  "dateTouched": "2024-03-25T14:21:43.746Z",
  "name": "Sendak Eggers",
  "game": "",
  "pronouns": "he/him",
  "description": "A half-orc druid who would really rather be left alone, please.",
  "traitSets": [
    {
      "name": "Distinctions",
      "description": "Trait set description",
      "nounSingular": "Distinction",
      "nounPlural": "Distinctions",
      "traits": [
        {
          "name": "Half-Orc",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [ "hinder" ],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Druid",
          "value": 10,
          "description": "Trait description",
          "traits": [],
          "sfx": [ "hinder" ],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Sage",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [ "hinder" ],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": true,
            "sfx": true,
            "subtraits": false
          },
          "location": "left",
          "style": {
            "header": "distinctions",
            "body": "distinctions"
          }
        }
      }
    },
    {
      "name": "Attributes",
      "description": "Trait set description",
      "nounSingular": "Attribute",
      "nounPlural": "Attributes",
      "traits": [
        {
          "name": "Strength",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Agility",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Wisdom",
          "value": 10,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": false,
            "sfx": false,
            "subtraits": false
          },
          "location": "attributes",
          "style": {
            "header": "attributes",
            "body": "attributes"
          }
        }
      }
    },
    {
      "name": "Values",
      "description": "Trait set description",
      "nounSingular": "Value",
      "nounPlural": "Values",
      "traits": [
        {
          "name": "Honor",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Wealth",
          "value": 4,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Kindness",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Justice",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Truth",
          "value": 12,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Power",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": false,
            "sfx": false,
            "subtraits": false
          },
          "location": "left",
          "style": {
            "header": "two-columns-compact",
            "body": "two-columns-compact"
          }
        }
      }
    },
    {
      "name": "Stress",
      "description": "Trait set description",
      "nounSingular": "Stress",
      "nounPlural": "Stress",
      "traits": [
        {
          "name": "Harm",
          "value": 10,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Stress",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Doubt",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": false,
            "sfx": false,
            "subtraits": false
          },
          "location": "right",
          "style": {
            "header": "stress",
            "body": "stress"
          }
        }
      }
    },
    {
      "name": "Signature Assets",
      "description": "Trait set description",
      "nounSingular": "Asset",
      "nounPlural": "Assets",
      "traits": [
        {
          "name": "Shillelagh",
          "value": 8,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "New Asset",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": true,
            "sfx": false,
            "subtraits": false
          },
          "location": "left",
          "style": {
            "header": "assets",
            "body": "assets"
          }
        }
      }
    },
    {
      "name": "Affiliations",
      "description": "Trait set description",
      "nounSingular": "Affiliation",
      "nounPlural": "Affiliations",
      "traits": [
        {
          "name": "Circle of the Moon",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Kingâ€™s Guard",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Biggetyburgh",
          "value": 6,
          "description": "Trait description",
          "traits": [],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": true,
            "sfx": false,
            "subtraits": false
          },
          "location": "left",
          "style": {
            "header": "resources",
            "body": "resources"
          }
        }
      }
    },
    {
      "name": "Skills",
      "description": "Trait set description",
      "nounSingular": "Skill",
      "nounPlural": "Skills",
      "traits": [
        {
          "name": "Athletics",
          "value": 6,
          "description": "Trait description",
          "traits": [
            {
              "name": "Jump",
              "value": 6,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            },
            {
              "name": "Swim",
              "value": 10,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            },
            {
              "name": "Climb",
              "value": 8,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            }
          ],
          "sfx": [],
          "tags": [],
          "custom": {}
        },
        {
          "name": "Knowledge",
          "value": 6,
          "description": "Trait description",
          "traits": [
            {
              "name": "Arcana",
              "value": 6,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            },
            {
              "name": "Nature",
              "value": 10,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            },
            {
              "name": "Society",
              "value": 8,
              "description": "",
              "traits": [],
              "sfx": [],
              "tags": [],
              "custom": {}
            }
          ],
          "sfx": [],
          "tags": [],
          "custom": {}
        }
      ],
      "sfx": [],
      "tags": [],
      "custom": {
        "cortexToolkit": {
          "features": {
            "description": false,
